### ISSUE TITLE
Incorrect documentation on DGJ for Surface Hub

### ISSUE THREAD

**Issue by 3017mark** [MicrosoftDocs/Devices-docs#178]
This feature is NOT available in our government community clouds and should be explicitly called out at the BEGINNING of this article.  This causes frustration and confusion on the part of our U.S. government customers.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 137ed04a-7df8-002f-809a-39b32b4cd602
* Version Independent ID: 346e83e3-03ae-9f86-7bce-6f416c65c871
* Content: [Microsoft Teams Rooms on Surface Hub - Surface Hub](https://learn.microsoft.com/en-us/surface-hub/surface-hub-teams-rooms?source=recommendations#third-party-meetings-on-surface-hub)
* Content Source: [surface-hub/surface-hub-teams-rooms.md](https://github.com/microsoftdocs/devices-docs/blob/public/surface-hub/surface-hub-teams-rooms.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @CoveMiner
* Microsoft Alias: **hachidan**

**Comment by DanPandre** [comment]
This feature is available.
