### ISSUE TITLE
edit page to say 50-inch

### ISSUE THREAD

**Issue by luriep** [MicrosoftDocs/Devices-docs#21]
[Enter feedback here]
This page title should be edited to make it clear it applies only to the 50-inch Surface Hub 2S (and not the new 85" Hub 2S) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecac0b0f-09ed-72a5-83b0-4068ada4f08e
* Version Independent ID: 3234298a-326c-a877-db4f-2206c73e43ae
* Content: [Surface Hub 2S tech specs - Surface Hub](https://docs.microsoft.com/en-us/surface-hub/surface-hub-2s-techspecs)
* Content Source: [surface-hub/surface-hub-2s-techspecs.md](https://github.com/microsoftdocs/devices-docs/blob/public/surface-hub/surface-hub-2s-techspecs.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
I've added this - thanks! It will show up later today ~ 5PM PST
