### ISSUE TITLE
Fact Check: Windows 10 Team to Windows 10 Pro or Enterprise is currently only available on Surface Hub 2S 50"

### ISSUE THREAD

**Issue by pazzo505** [MicrosoftDocs/Devices-docs#62]
[Enter feedback here]

The migration from Windows 10 Team to Windows 10 Pro or Enterprise should be available for both 50" and 85".
Please double check the 3rd sentence in the Reference section 
---------------------------
Migrating from Windows 10 Team to Windows 10 Pro or Enterprise is currently only available on Surface Hub 2S 50". Learn more at Migrate to Windows 10 Pro or Enterprise on Surface Hub 2.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30de80eb-59f0-344b-dd80-4f4951757ea2
* Version Independent ID: 83531d9c-6491-63fb-9ba5-005d16a1ea6d
* Content: [Surface Hub 2S 85-inch - Surface Hub](https://docs.microsoft.com/en-us/surface-hub/surface-hub-2s-85)
* Content Source: [surface-hub/surface-hub-2s-85.md](https://github.com/microsoftdocs/devices-docs/blob/public/surface-hub/surface-hub-2s-85.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
No this was only for 50"
